// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using flytt2021.Data;

namespace flytt2021.Migrations
{
    [DbContext(typeof(FlyttDbContext))]
    partial class FlyttDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("flytt2021.Data.BoxOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BoxOwners");
                });

            modelBuilder.Entity("flytt2021.Data.Movingbox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("BoxOwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Contents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DestinationFloor")
                        .HasColumnType("int");

                    b.Property<bool>("IsUnpacked")
                        .HasColumnType("bit");

                    b.Property<string>("Marking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BoxOwnerId");

                    b.ToTable("Movingboxes");
                });

            modelBuilder.Entity("flytt2021.Data.Movingbox", b =>
                {
                    b.HasOne("flytt2021.Data.BoxOwner", "BoxOwner")
                        .WithMany()
                        .HasForeignKey("BoxOwnerId");

                    b.Navigation("BoxOwner");
                });
#pragma warning restore 612, 618
        }
    }
}
